title: "Bigstark"
email: bigstarkmail@gmail.com
timezone: UTC
baseurl: "/blog1"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Sal
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  bigstark:
    name: Sal
    display_name: Sal
    avatar: 'assets/images/sal.png'
    email: bisgtarkmail@gmail.com
    web: https://bigstark.in/
    #twitter: https://twitter.com
    #description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  kasuta:
    name: Kasuta Arya
    display_name: Kasuta Arya
    avatar: 'assets/images/john.png'
    email: bigstarkmail@gmail.com
    web: https://bigstark.in/
    twitter: https://twitter.com/kasuta_arya
    #description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Social
social:
  #instagram: https://www.instagram.com/bootstrapstarter/
  #facebook: https://www.facebook.com/bootstrapstartercom-346329609045284
  twitter: https://twitter.com/kasuta_arya

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
